import type { Instructor, LessonGroup, Student } from "./types";

export const seedStudents: Array<Student> = [
  {
    id: "stu-1",
    name: "Alex Rivera",
    age: 8,
    level: 2,
    medicalInfo: "EpiPen in jacket pocket",
    parentName: "Maria Rivera",
    parentPhone: "555-0101",
    parentEmail: "maria.r@example.com",
    notes: "Nervous on steep blues; prefers morning.",
  },
  {
    id: "stu-2",
    name: "Jordan Chen",
    age: 12,
    level: 4,
    medicalInfo: "None",
    parentName: "Sam Chen",
    parentPhone: "555-0102",
    parentEmail: "sam.chen@example.com",
    notes: "Wants to work on carving; strong skier.",
  },
  {
    id: "stu-3",
    name: "Taylor Brooks",
    age: 10,
    level: 3,
    medicalInfo: "Asthma — inhaler before lunch",
    parentName: "Chris Brooks",
    parentPhone: "555-0103",
    parentEmail: "chris.b@example.com",
    notes: "Pair with patient instructor; first time group lesson.",
  },
  {
    id: "stu-4",
    name: "Riley O'Neil",
    age: 9,
    level: 2,
    medicalInfo: "None",
    parentName: "Pat O'Neil",
    parentPhone: "555-0104",
    parentEmail: "pat.oneil@example.com",
    notes: "Snowboard-curious; helmet fits snug.",
  },
  {
    id: "stu-5",
    name: "Morgan Singh",
    age: 14,
    level: 5,
    medicalInfo: "None",
    parentName: "Priya Singh",
    parentPhone: "555-0105",
    parentEmail: "priya.s@example.com",
    notes: "Racing program track; needs technical drills.",
  },
  {
    id: "stu-6",
    name: "Casey Miller",
    age: 7,
    level: 1,
    medicalInfo: "None",
    parentName: "Jamie Miller",
    parentPhone: "555-0106",
    parentEmail: "jamie.m@example.com",
    notes: "Beginner magic carpet only; parents late pickup Fridays.",
  },
  {
    id: "stu-7",
    name: "Leo Martinez",
    age: 5,
    level: 1,
    medicalInfo: "None",
    parentName: "Elena Martinez",
    parentPhone: "555-0107",
    parentEmail: "elena.m@example.com",
    notes: "First season; needs frequent glove and snack breaks.",
  },
  {
    id: "stu-8",
    name: "Nina Patel",
    age: 6,
    level: 2,
    medicalInfo: "None",
    parentName: "Vik Patel",
    parentPhone: "555-0108",
    parentEmail: "vik.p@example.com",
    notes: "Confident on mellow greens; working on parallel.",
  },
  {
    id: "stu-9",
    name: "Drew Kim",
    age: 11,
    level: 3,
    medicalInfo: "None",
    parentName: "Min Kim",
    parentPhone: "555-0109",
    parentEmail: "min.k@example.com",
    notes: "Switches edges late on steeper blues.",
  },
  {
    id: "stu-10",
    name: "Avery Walsh",
    age: 10,
    level: 2,
    medicalInfo: "None",
    parentName: "Quinn Walsh",
    parentPhone: "555-0110",
    parentEmail: "quinn.w@example.com",
    notes: "Ride-share pickup; photo release on file.",
  },
  {
    id: "stu-11",
    name: "Chris Nguyen",
    age: 12,
    level: 4,
    medicalInfo: "None",
    parentName: "Linh Nguyen",
    parentPhone: "555-0111",
    parentEmail: "linh.n@example.com",
    notes: "Interested in bumps and trees next.",
  },
  {
    id: "stu-12",
    name: "Sam Okonkwo",
    age: 5,
    level: 1,
    medicalInfo: "None",
    parentName: "Amara Okonkwo",
    parentPhone: "555-0112",
    parentEmail: "amara.o@example.com",
    notes: "Tiny boots; double-check rental fit each morning.",
  },
  {
    id: "stu-13",
    name: "Rowan Blake",
    age: 9,
    level: 3,
    medicalInfo: "Nut allergy — no shared snacks",
    parentName: "Jules Blake",
    parentPhone: "555-0113",
    parentEmail: "jules.b@example.com",
    notes: "Bring own labeled snack pack.",
  },
  {
    id: "stu-14",
    name: "Sage Lopez",
    age: 6,
    level: 2,
    medicalInfo: "None",
    parentName: "Diego Lopez",
    parentPhone: "555-0114",
    parentEmail: "diego.l@example.com",
    notes: "Wears glasses under goggles.",
  },
  {
    id: "stu-15",
    name: "Quinn Park",
    age: 10,
    level: 3,
    medicalInfo: "None",
    parentName: "Hana Park",
    parentPhone: "555-0115",
    parentEmail: "hana.p@example.com",
    notes: "Prefers ski; sibling in snowboard group.",
  },
  {
    id: "stu-16",
    name: "Hayden Roy",
    age: 11,
    level: 3,
    medicalInfo: "None",
    parentName: "Parker Roy",
    parentPhone: "555-0116",
    parentEmail: "parker.r@example.com",
    notes: "Strong stamina; ok with longer laps.",
  },
  {
    id: "stu-17",
    name: "Frankie Moss",
    age: 8,
    level: 2,
    medicalInfo: "None",
    parentName: "Reese Moss",
    parentPhone: "555-0117",
    parentEmail: "reese.m@example.com",
    notes: "Unassigned — flexible for makeup lesson placement.",
  },
  {
    id: "stu-18",
    name: "Kai Brennan",
    age: 14,
    level: 5,
    medicalInfo: "None",
    parentName: "Sean Brennan",
    parentPhone: "555-0118",
    parentEmail: "sean.b@example.com",
    notes: "Unassigned — waiting on Sat PM advanced roster.",
  },
];

export const seedInstructors: Array<Instructor> = [
  {
    id: "ins-1",
    name: "Sam Winter",
    phone: "ext 2201",
    email: "sam.winter@resort.com",
    disciplines: ["ski"],
    notes: "Great with kids; Level 1–3 ski.",
  },
  {
    id: "ins-2",
    name: "Riley Frost",
    phone: "ext 2202",
    email: "riley.frost@resort.com",
    disciplines: ["snowboard"],
    notes: "Park & freestyle snowboard specialist.",
  },
  {
    id: "ins-3",
    name: "Jamie Peak",
    phone: "ext 2203",
    email: "jamie.peak@resort.com",
    disciplines: ["ski", "snowboard"],
    notes: "PSIA-AASI; prefers mixed-discipline groups.",
  },
  {
    id: "ins-4",
    name: "Skyler Cruz",
    phone: "ext 2204",
    email: "skyler.cruz@resort.com",
    disciplines: ["ski"],
    notes: "Advanced ski; steep/corridor comfort.",
  },
  {
    id: "ins-5",
    name: "Blake Hart",
    phone: "ext 2205",
    email: "blake.hart@resort.com",
    disciplines: ["ski"],
    notes: "Loves teaching progression; strong on gradual terrain parks.",
  },
  {
    id: "ins-6",
    name: "Dana Reyes",
    phone: "ext 2206",
    email: "dana.reyes@resort.com",
    disciplines: ["snowboard"],
    notes: "Beginner-friendly; clear verbal cues for switch riding.",
  },
];

export const seedGroups: Array<LessonGroup> = [
  {
    id: "grp-1",
    studentIds: ["stu-1", "stu-6"],
    instructorIds: ["ins-1"],
    leadInstructorId: "ins-1",
    day: "Sat",
    time: "AM",
    level: 2,
    ageRange: "7-12",
    notes: "Focus on wedge stops and confidence.",
  },
  {
    id: "grp-2",
    studentIds: ["stu-2", "stu-5"],
    instructorIds: ["ins-4"],
    leadInstructorId: "ins-4",
    day: "Sat",
    time: "PM",
    level: 5,
    ageRange: "7-12",
    notes: "Edge engagement and short turns.",
  },
  {
    id: "grp-3",
    studentIds: ["stu-3", "stu-9", "stu-13"],
    instructorIds: ["ins-3"],
    leadInstructorId: "ins-3",
    day: "Sun",
    time: "AM",
    level: 3,
    ageRange: "7-12",
    notes: "Mixed confidence; lots of side-slipping practice.",
  },
  {
    id: "grp-4",
    studentIds: ["stu-7", "stu-12"],
    instructorIds: ["ins-1"],
    leadInstructorId: "ins-1",
    day: "Sat",
    time: "AM",
    level: 1,
    ageRange: "4-6",
    notes: "Rope tow etiquette and stopping in control.",
  },
  {
    id: "grp-5",
    studentIds: ["stu-4", "stu-10"],
    instructorIds: ["ins-2"],
    leadInstructorId: "ins-2",
    day: "Sun",
    time: "PM",
    level: 2,
    ageRange: "7-12",
    notes: "Heel-to-toe flow and falling leaf refinement.",
  },
  {
    id: "grp-6",
    studentIds: ["stu-11"],
    instructorIds: ["ins-4"],
    leadInstructorId: "ins-4",
    day: "Fri",
    time: "PM",
    level: 4,
    ageRange: "7-12",
    notes: "Private-ish small group; rhythm on carved turns.",
  },
  {
    id: "grp-7",
    studentIds: ["stu-15", "stu-16"],
    instructorIds: ["ins-5"],
    leadInstructorId: "ins-5",
    day: "Mon",
    time: "FULL_DAY",
    level: 3,
    ageRange: "7-12",
    notes: "Camp day — indoor video review at lunch.",
  },
  {
    id: "grp-8",
    studentIds: ["stu-8", "stu-14"],
    instructorIds: ["ins-6"],
    leadInstructorId: "ins-6",
    day: "Tue",
    time: "AM",
    level: 2,
    ageRange: "4-6",
    notes: "J-bars only; working toward linked heelside turns.",
  },
];
